# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - default_assignees:
      - "localheinz"
    default_reviewers:
      - "localheinz"
    directory: "/"
    ignored_updates:
      - match:
          dependency_name: "composer-plugin-api"
      - match:
          dependency_name: "composer/composer"
      - match:
          dependency_name: "localheinz/composer-json-normalizer"
      - match:
          dependency_name: "localheinz/json-normalizer"
      - match:
          dependency_name: "phpunit/phpunit"
      - match:
          dependency_name: "sebastian/diff"
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
