# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - default_assignees:
      - "localheinz"
    default_labels:
      - "dependency"
    default_reviewers:
      - "localheinz"
    directory: "/"
    package_manager: "github_actions"
    update_schedule: "daily"

  - automerged_updates:
      - match:
          dependency_type: "development"
    default_assignees:
      - "localheinz"
    default_labels:
      - "dependency"
    default_reviewers:
      - "localheinz"
    directory: "/"
    ignored_updates:
      - match:
          dependency_name: "composer-plugin-api"
      - match:
          dependency_name: "composer/composer"
      - match:
          dependency_name: "localheinz/composer-json-normalizer"
      - match:
          dependency_name: "localheinz/json-normalizer"
    package_manager: "php:composer"
    update_schedule: "daily"
    version_requirement_updates: "increase_versions"
