# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - commit_message:
      include_scope: true
      prefix: "Build"
    default_labels:
      - "dependency"
    directory: "/"
    ignored_updates:
      - match:
          dependency_name: "composer-plugin-api"
      - match:
          dependency_name: "composer/composer"
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"

  - commit_message:
      include_scope: true
      prefix: "Build"
    default_labels:
      - "dependency"
    directory: "/tools/"
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
