# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

        dependencies:
          - "locked"

    env:
      COMPOSER_NORMALIZE_PHAR: ".build/phar/composer-normalize.phar"
      COMPOSER_NORMALIZE_PHAR_SIGNATURE: ".build/phar/composer-normalize.phar.asc"
      COMPOSER_VERSION: "2.2.5"
      GPG_KEYS: ".build/phar/keys.asc"
      GPG_KEYS_ENCRYPTED: "phar/keys.asc.gpg"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.4.0"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.16.0"
        with:
          coverage: "none"
          extensions: "none, ctype, dom, json, mbstring, phar, simplexml, tokenizer, xml, xmlwriter"
          php-version: "${{ matrix.php-version }}"

      - name: "Determine composer cache directory"
        uses: "./.github/actions/composer/composer/determine-cache-directory"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.1.7"
        with:
          path: "${{ env.COMPOSER_CACHE_DIR }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install ${{ matrix.dependencies }} dependencies with composer"
        uses: "ergebnis/.github/actions/composer/install@1.2.1"
        with:
          dependencies: "${{ matrix.dependencies }}"

      - name: "Require composer/composer"
        run: "composer require composer/composer:${{ env.COMPOSER_VERSION }} --no-interaction --no-progress"

      - name: "Validate configuration for humbug/box"
        run: ".phive/box validate box.json"

      - name: "Compile composer-normalize.phar with humbug/box"
        run: ".phive/box compile --config=box.json"

      - name: "Show info about composer-normalize.phar with humbug/box"
        run: ".phive/box info ${{ env.COMPOSER_NORMALIZE_PHAR }}"

      - name: "Run composer-normalize.phar"
        run: "${{ env.COMPOSER_NORMALIZE_PHAR }}"

      - name: "Show gpg version"
        run: "gpg --version"

      - name: "Decrypt keys.asc.gpg with gpg"
        run: "gpg --batch --output ${{ env.GPG_KEYS }} --passphrase \"${{ secrets.GPG_DECRYPT_PASSPHRASE }}\" --yes --decrypt ${{ env.GPG_KEYS_ENCRYPTED }}"

      - name: "Import keys from keys.asc with gpg"
        run: "gpg --batch --import ${{ env.GPG_KEYS }}"

      - name: "Sign composer-normalize.phar with gpg"
        run: "gpg --armor --local-user \"${{ secrets.GPG_LOCAL_USER }}\" --output ${{ env.COMPOSER_NORMALIZE_PHAR_SIGNATURE }} --passphrase \"${{ secrets.GPG_KEY_PASSPHRASE }}\" --pinentry-mode loopback --yes --detach-sig ${{ env.COMPOSER_NORMALIZE_PHAR }}"

      - name: "Remove decrypted keys.asc"
        run: "rm ${{ env.GPG_KEYS }}"

      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"

      - name: "Create release"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: "Upload release assets"
        uses: "actions/github-script@v5"
        env:
          FOO: "${{ env.GITHUB_WORKSPACE }}"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const fs = require("fs");

            const files = [
              {
                name: "composer-normalize.phar",
                path: process.env.COMPOSER_NORMALIZE_PHAR,
              },
              {
                name: "composer-normalize.phar.asc",
                path: process.env.COMPOSER_NORMALIZE_PHAR_SIGNATURE,
              },
            ];

            for (const file of files) {
              try {
                await github.rest.repos.uploadReleaseAsset({
                  data: fs.readFileSync(file.path),
                  name: file.name,
                  origin: process.env.RELEASE_UPLOAD_URL,
                  owner: context.repo.owner,
                  release_id: process.env.RELEASE_ID,
                  repo: context.repo.repo,
                });
              } catch (error) {
                core.setFailed(error.message);
              }
            }
