# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Schema"

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  schema:
    name: "Schema"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Verify schema is up-to-date"
        run: "diff -u ./resource/schema.json <(wget -qO- 'https://getcomposer.org/schema.json')"
