# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Schema"

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  schema:
    name: "Schema"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Download schema"
        run: "wget --output-document=resource/schema.json https://getcomposer.org/schema.json"

      - name: "Show diff"
        run: "git diff resource/schema.json"

      - name: "Commit updated schema"
        uses: "stefanzweifel/git-auto-commit-action@v2.5.0"
        with:
          branch: "master"
          commit_message: "Enhancement: Update schema.json"
          file_pattern: "resource\\/schema\\.json"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN_LOCALHEINZ }}"
